# Generated by Django 4.2.1 on 2023-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient', models.CharField(max_length=258)),
                ('notification_type', models.CharField(choices=[('EMAIL', 'EMAIL'), ('SMS', 'SMS')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10)),
                ('event', models.CharField(max_length=64)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
