version: '3.1'

services:
  postgres:
    restart: always
    image: postgres:15.3
    volumes:
      - ../db/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_USER_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: go2-pg

  rabbitmq:
    restart: always
    image: rabbitmq:3.11.16
    volumes:
      - ../lib/rabbitmq:/var/lib/rabbitmq
      - ../logs/rabbitmq:/var/log/rabbitmq
      - ../scripts/rabbitmq:/tmp/scripts
    hostname: "go2-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
    ports:
      - "${RABBITMQ_PORT}:5672"
    container_name: go2-rabbitmq

  web:
    restart: always
    build:
      context: ../
    image: go2-web
    volumes:
      - ../:/srv/go2
    container_name: go2-web
    working_dir: "/srv/go2"
    command: "/usr/sbin/sshd -D"
